import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(packageRoot, "../..");
const assetRoot = path.join(repoRoot, "crates", "report", "assets");
const checkOnly = process.argv.includes("--check");

const result = await build({
  absWorkingDir: packageRoot,
  entryPoints: ["src/index.tsx"],
  bundle: true,
  minify: true,
  format: "iife",
  platform: "browser",
  target: ["es2022"],
  legalComments: "none",
  sourcemap: false,
  write: false,
  outdir: "dist",
  define: {
    "process.env.NODE_ENV": '"production"',
  },
});

const generatedHeader = "/* Generated by packages/report-ui/scripts/build.mjs; do not edit. */\n";
const assets = new Map();
for (const output of result.outputFiles) {
  const extension = path.extname(output.path);
  if (extension === ".js" || extension === ".css") {
    assets.set(`report-ui${extension}`, generatedHeader + output.text.trimEnd() + "\n");
  }
}

for (const expected of ["report-ui.js", "report-ui.css"]) {
  if (!assets.has(expected)) {
    throw new Error(`esbuild did not emit ${expected}`);
  }
}
if (assets.get("report-ui.js").toLowerCase().includes("</script")) {
  throw new Error("generated JavaScript contains an unsafe closing script token");
}

await mkdir(assetRoot, { recursive: true });
const stale = [];
for (const [name, contents] of assets) {
  const destination = path.join(assetRoot, name);
  if (checkOnly) {
    const current = await readFile(destination, "utf8").catch(() => "");
    if (current !== contents) stale.push(name);
  } else {
    await writeFile(destination, contents, "utf8");
  }
}

if (stale.length > 0) {
  throw new Error(`generated report assets are stale: ${stale.join(", ")}; run npm run build`);
}

console.log(checkOnly ? "report assets are deterministic and current" : "wrote deterministic report assets");
