import type { ReportModel } from "../src/model";

export const sampleModel: ReportModel = {
  schemaVersion: "tomorrowci.report/v1",
  evidenceSchemaVersion: 2,
  run: {
    id: "run-verified",
    toolVersion: "0.2.0-alpha.1",
    ecosystem: "NODE",
    source: "fixture",
    commitSha: "0123456789abcdef",
    configHash: "sha256:config",
    startedAt: "2026-08-11T00:00:00Z",
    finishedAt: "2026-08-11T00:01:00Z",
  },
  baseline: {
    runtime: "20",
    dependencies: "locked",
    declaredBy: "config",
  },
  frontier: {
    observed: true,
    authorization: "AUTHORIZED_BY_VERIFIED_FRONTIER",
    horizonLabel: "22",
    firstFailingScenario: "node22",
    lastPassingScenario: "baseline",
    grade: "OBSERVED",
    changedAxes: ["RUNTIME"],
    failureHash: "sha256:failure",
    failureSummary: "Removed runtime API",
    replayCommand: "tomorrowci replay run-verified --scenario node22",
    notes: ["<img data-xss onerror=alert(1)> remains text"],
  },
  scenarios: [
    {
      order: 0,
      id: "baseline",
      isBaseline: true,
      runtime: "20",
      dependencies: "locked",
      axesChanged: [],
      verdict: "PASS",
      tone: "pass",
      durationMs: 100,
      testAttempts: 1,
      image: "node:20",
      imageDigest: "node@sha256:baseline",
      failureKind: null,
      failureSummary: null,
      links: {
        scenario: "scenarios/baseline/scenario.json",
        environment: "scenarios/baseline/environment.json",
        result: "scenarios/baseline/result.json",
        replayDescriptor: "scenarios/baseline/replay.json",
        replays: "scenarios/baseline/replays/",
      },
    },
    {
      order: 1,
      id: "node22",
      isBaseline: false,
      runtime: "22",
      dependencies: "locked",
      axesChanged: ["RUNTIME"],
      verdict: "FAIL",
      tone: "fail",
      durationMs: 125,
      testAttempts: 2,
      image: "node:22",
      imageDigest: "node@sha256:candidate",
      failureKind: "RemovedRuntimeApi",
      failureSummary: "crypto.createCipher is unavailable",
      links: {
        scenario: "scenarios/node22/scenario.json",
        environment: "scenarios/node22/environment.json",
        result: "scenarios/node22/result.json",
        replayDescriptor: "scenarios/node22/replay.json",
        replays: "scenarios/node22/replays/",
      },
    },
    {
      order: 2,
      id: "blocked-candidate",
      isBaseline: false,
      runtime: "24",
      dependencies: "locked",
      axesChanged: ["RUNTIME"],
      verdict: "BLOCKED",
      tone: "blocked",
      durationMs: null,
      testAttempts: 0,
      image: null,
      imageDigest: null,
      failureKind: null,
      failureSummary: null,
      links: {
        scenario: "scenarios/blocked-candidate/scenario.json",
        environment: "scenarios/blocked-candidate/environment.json",
        result: "scenarios/blocked-candidate/result.json",
        replayDescriptor: "scenarios/blocked-candidate/replay.json",
        replays: "scenarios/blocked-candidate/replays/",
      },
    },
  ],
  replayAttempts: [
    {
      scenarioId: "node22",
      attempt: 1,
      resultHref: "scenarios/node22/replays/attempt-1/result.json",
    },
  ],
  denominator: {
    total: 3,
    pass: 1,
    fail: 1,
    flaky: 0,
    blocked: 1,
    unsupported: 0,
    inconclusive: 0,
    notRun: 0,
  },
  evidenceLinks: [
    { label: "Run manifest", href: "run.json", description: "Verified semantic source." },
    { label: "Checksums", href: "checksums.txt", description: "Exact bundle inventory." },
  ],
};
