//! Generate examples/reports from a scripted Python runtime-break scan.

use anyhow::Result;
use std::collections::HashMap;
use std::path::PathBuf;
use tomorrowci_adapter_python::PythonAdapter;
use tomorrowci_adapters::EcosystemAdapter;
use tomorrowci_core::Config;
use tomorrowci_runner::{scan_with_executor, ScriptedExecutor};

fn main() -> Result<()> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let fixture = root.join("fixtures/python-runtime-break");
    let out_dir = root.join("examples/reports/python-runtime-break");
    std::fs::create_dir_all(&out_dir)?;

    let adapter = PythonAdapter;
    let det = adapter.detect(&fixture);
    if !det.supported {
        anyhow::bail!("fixture not detected as python");
    }

    let mut cfg = Config::load_file(&fixture.join(".tomorrowci.yml")).unwrap_or_default();
    cfg.candidates.dependencies.latest_allowed = false;
    cfg.execution.reruns_on_failure = 2;

    let mut map = HashMap::new();
    map.insert("baseline".into(), vec![0]);
    map.insert("py310-locked".into(), vec![1, 1]);
    map.insert("py311-locked".into(), vec![1, 1]);
    map.insert("py312-locked".into(), vec![1, 1]);
    let exec = ScriptedExecutor::new(map)
        .with_stderr("ImportError: cannot import name 'MutableMapping' from 'collections'");

    let outcome = scan_with_executor(&fixture, &adapter, cfg, &exec, det.detection)?;
    // Copy durable demo artifacts
    for name in [
        "report.html",
        "run.json",
        "metrics.json",
        "job-summary.md",
        "summary.txt",
        "frontier.json",
    ] {
        let src = outcome.evidence_root.join(name);
        if src.exists() {
            std::fs::copy(&src, out_dir.join(name))?;
        }
    }
    std::fs::write(
        out_dir.join("README.md"),
        format!(
            "# Demo report: python-runtime-break\n\nGenerated by `cargo run -p tomorrowci-gen-demo`.\n\n- Run id: `{}`\n- Frontier observed: {}\n- Horizon: {:?}\n\nOpen `report.html` locally (no backend).\n",
            outcome.manifest.run_id,
            outcome.manifest.frontier.observed,
            outcome.manifest.frontier.horizon_label
        ),
    )?;
    println!("wrote demo to {}", out_dir.display());
    println!("{}", outcome.metrics.summary_line());
    Ok(())
}
